version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "io.quarkus:quarkus-bom"
      - dependency-name: "org.apache.camel:*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 14
