package io.quarkus.updates.core;

import static org.openrewrite.maven.Assertions.pomXml;

import java.nio.file.Path;

import org.junit.jupiter.api.Test;
import org.openrewrite.java.JavaParser;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;
import org.openrewrite.test.TypeValidation;

public class CoreUpdate37Test implements RewriteTest {

    @Override
    public void defaults(RecipeSpec spec) {
        CoreTestUtil.recipe(spec, Path.of("quarkus-updates", "core", "3.7.alpha1.yaml"), "3.7.0.CR1")
                .parser(JavaParser.fromJavaVersion().logCompilationWarningsAndErrors(true))
                .typeValidationOptions(TypeValidation.none());
    }

    @Test
    void testMavenCompilerJavaVersion() {
        //language=xml
        rewriteRun(pomXml("""
            <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>io.quarkus.bot</groupId>
                <artifactId>release</artifactId>
                <version>999-SNAPSHOT</version>
                <properties>
                    <maven.compiler.release>11</maven.compiler.release>
                    <maven.compiler.target>11</maven.compiler.target>
                    <maven.compiler.source>11</maven.compiler.source>
                </properties>
            </project>
            """,
            """
            <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>io.quarkus.bot</groupId>
                <artifactId>release</artifactId>
                <version>999-SNAPSHOT</version>
                <properties>
                    <maven.compiler.release>17</maven.compiler.release>
                    <maven.compiler.target>17</maven.compiler.target>
                    <maven.compiler.source>17</maven.compiler.source>
                </properties>
            </project>
            """));

        //language=xml
        rewriteRun(pomXml("""
            <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>io.quarkus.bot</groupId>
                <artifactId>release</artifactId>
                <version>999-SNAPSHOT</version>
                <properties>
                    <maven.compiler.release>21</maven.compiler.release>
                    <maven.compiler.target>21</maven.compiler.target>
                    <maven.compiler.source>21</maven.compiler.source>
                </properties>
            </project>
            """));
    }

    @Test
    void testMavenPluginUpdates() {
        //language=xml
        rewriteRun(pomXml("""
            <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>io.quarkus.bot</groupId>
                <artifactId>release</artifactId>
                <version>999-SNAPSHOT</version>

                <properties>
                    <compiler-plugin.version>3.11.0</compiler-plugin.version>
                    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
                    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
                    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
                    <skipITs>true</skipITs>
                    <surefire-plugin.version>3.1.2</surefire-plugin.version>
                </properties>

                <build>
                    <plugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-compiler-plugin</artifactId>
                            <version>${compiler-plugin.version}</version>
                            <configuration>
                                <compilerArgs>
                                    <arg>-parameters</arg>
                                </compilerArgs>
                            </configuration>
                        </plugin>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-surefire-plugin</artifactId>
                            <version>${surefire-plugin.version}</version>
                            <configuration>
                                <systemPropertyVariables>
                                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                                    <maven.home>${maven.home}</maven.home>
                                </systemPropertyVariables>
                            </configuration>
                        </plugin>
                    </plugins>
                </build>
            </project>
            """,
            """
            <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>io.quarkus.bot</groupId>
                <artifactId>release</artifactId>
                <version>999-SNAPSHOT</version>

                <properties>
                    <compiler-plugin.version>3.12.1</compiler-plugin.version>
                    <maven.compiler.release>17</maven.compiler.release>
                    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
                    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
                    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
                    <skipITs>true</skipITs>
                    <surefire-plugin.version>3.2.3</surefire-plugin.version>
                </properties>

                <build>
                    <plugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-compiler-plugin</artifactId>
                            <version>${compiler-plugin.version}</version>
                            <configuration>
                                <compilerArgs>
                                    <arg>-parameters</arg>
                                </compilerArgs>
                            </configuration>
                        </plugin>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-surefire-plugin</artifactId>
                            <version>${surefire-plugin.version}</version>
                            <configuration>
                                <systemPropertyVariables>
                                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                                    <maven.home>${maven.home}</maven.home>
                                </systemPropertyVariables>
                            </configuration>
                        </plugin>
                    </plugins>
                </build>
            </project>
            """));
    }

    @Test
    void testMavenPluginUpdatesDefaultGroupId() {
        //language=xml
        rewriteRun(pomXml("""
            <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>io.quarkus.bot</groupId>
                <artifactId>release</artifactId>
                <version>999-SNAPSHOT</version>

                <properties>
                    <compiler-plugin.version>3.11.0</compiler-plugin.version>
                    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
                    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
                    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
                    <skipITs>true</skipITs>
                    <surefire-plugin.version>3.1.2</surefire-plugin.version>
                </properties>

                <build>
                    <plugins>
                        <plugin>
                            <artifactId>maven-compiler-plugin</artifactId>
                            <version>${compiler-plugin.version}</version>
                            <configuration>
                                <compilerArgs>
                                    <arg>-parameters</arg>
                                </compilerArgs>
                            </configuration>
                        </plugin>
                        <plugin>
                            <artifactId>maven-surefire-plugin</artifactId>
                            <version>${surefire-plugin.version}</version>
                            <configuration>
                                <systemPropertyVariables>
                                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                                    <maven.home>${maven.home}</maven.home>
                                </systemPropertyVariables>
                            </configuration>
                        </plugin>
                    </plugins>
                </build>
            </project>
            """,
            """
            <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>io.quarkus.bot</groupId>
                <artifactId>release</artifactId>
                <version>999-SNAPSHOT</version>

                <properties>
                    <compiler-plugin.version>3.12.1</compiler-plugin.version>
                    <maven.compiler.release>17</maven.compiler.release>
                    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
                    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
                    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
                    <skipITs>true</skipITs>
                    <surefire-plugin.version>3.2.3</surefire-plugin.version>
                </properties>

                <build>
                    <plugins>
                        <plugin>
                            <artifactId>maven-compiler-plugin</artifactId>
                            <version>${compiler-plugin.version}</version>
                            <configuration>
                                <compilerArgs>
                                    <arg>-parameters</arg>
                                </compilerArgs>
                            </configuration>
                        </plugin>
                        <plugin>
                            <artifactId>maven-surefire-plugin</artifactId>
                            <version>${surefire-plugin.version}</version>
                            <configuration>
                                <systemPropertyVariables>
                                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                                    <maven.home>${maven.home}</maven.home>
                                </systemPropertyVariables>
                            </configuration>
                        </plugin>
                    </plugins>
                </build>
            </project>
            """));
    }

    @Test
    void testJpaModelgenNoChanges() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                    </properties>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """));
    }

    @Test
    void testJpaModelgenOldDependency() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.hibernate</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>5.4.3.Final</version>
                        </dependency>
                    </dependencies>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                    </properties>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """));
    }

    @Test
    void testJpaModelgenNewDependency() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>6.1.2.Final</version>
                            <scope>provided</scope>
                        </dependency>
                    </dependencies>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                    </properties>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """));
    }

    @Test
    void testJpaModelgenNewDependencyManagedByQuarkusBom() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>3.6.4</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>6.1.2.Final</version>
                            <scope>provided</scope>
                        </dependency>
                    </dependencies>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                    </properties>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>3.7.0.CR1</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                            <version>6.4.1.Final</version>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """));
    }

    @Test
    void testJpaModelgenExistingConfig() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>6.1.2.Final</version>
                        </dependency>
                    </dependencies>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <proc>none</proc>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                    </properties>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <proc>none</proc>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """));
    }

    @Test
    void testJpaModelgenAnotherProcessor() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>6.1.2.Final</version>
                        </dependency>
                    </dependencies>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <proc>none</proc>
                                    <annotationProcessorPaths>
                                        <annotationProcessorPath>
                                            <groupId>another.annotation</groupId>
                                            <artifactId>processor</artifactId>
                                        </annotationProcessorPath>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                    </properties>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <proc>none</proc>
                                    <annotationProcessorPaths>
                                        <annotationProcessorPath>
                                            <groupId>another.annotation</groupId>
                                            <artifactId>processor</artifactId>
                                        </annotationProcessorPath>
                                        <annotationProcessorPath>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                        </annotationProcessorPath>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """));
    }

    @Test
    void testJpaModelgenAnnotationProcessorAlreadyPresent() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>6.1.2.Final</version>
                        </dependency>
                    </dependencies>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                    </properties>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """));
    }

    @Test
    void testJpaModelgenOldJpaModelgenAnnotationProcessorAlreadyPresent() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>3.6.4</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>6.1.2.Final</version>
                        </dependency>
                    </dependencies>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                    </properties>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>3.7.0.CR1</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                            <version>6.4.1.Final</version>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """));
    }

    @Test
    void testJpaModelgenOldJpaModelgenAnnotationProcessorAlreadyPresentWithOutdatedVersion() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>3.6.4</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>6.1.2.Final</version>
                        </dependency>
                    </dependencies>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                            <version>5.6.15.Final</version>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                    </properties>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>3.7.0.CR1</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                            <version>6.4.1.Final</version>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """));
    }

    @Test
    void testJpaModelgenNoBuildSection() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>3.6.4</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>6.1.2.Final</version>
                            <scope>provided</scope>
                        </dependency>
                    </dependencies>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                    </properties>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>3.7.0.CR1</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <build>
                        <plugins>
                            <plugin>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                            <version>6.4.1.Final</version>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """));
    }

    @Test
    void testJpaModelgenNoMavenCompilerPlugin() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>3.6.4</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>6.1.2.Final</version>
                            <scope>provided</scope>
                        </dependency>
                    </dependencies>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-jar-plugin</artifactId>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                    </properties>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>3.7.0.CR1</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-jar-plugin</artifactId>
                            </plugin>
                            <plugin>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                            <version>6.4.1.Final</version>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """));
    }

    @Test
    void testSyncVersion() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <quarkus.version>3.6.4</quarkus.version>
                    </properties>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>${quarkus.version}</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                            <version>6.2.13.Final</version>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                        <quarkus.version>3.7.0.CR1</quarkus.version>
                    </properties>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>${quarkus.version}</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.12.1</version>
                                <configuration>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.hibernate.orm</groupId>
                                            <artifactId>hibernate-jpamodelgen</artifactId>
                                            <version>6.4.1.Final</version>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """));
    }

    @Test
    void testResteasyClientRenaming() {
        //language=xml
        rewriteRun(pomXml("""
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <quarkus.version>3.6.4</quarkus.version>
                    </properties>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>${quarkus.version}</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-rest-client</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-rest-client-jackson</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-rest-client-jaxb</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-rest-client-jsonb</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-rest-client-mutiny</artifactId>
                        </dependency>
                    </dependencies>
                </project>
                """,
                """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>io.quarkus.bot</groupId>
                    <artifactId>release</artifactId>
                    <version>999-SNAPSHOT</version>
                    <properties>
                        <maven.compiler.release>17</maven.compiler.release>
                        <quarkus.version>3.7.0.CR1</quarkus.version>
                    </properties>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bom</artifactId>
                                <version>${quarkus.version}</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-resteasy-client</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-resteasy-client-jackson</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-resteasy-client-jaxb</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-resteasy-client-jsonb</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-resteasy-client-mutiny</artifactId>
                        </dependency>
                    </dependencies>
                </project>
                """));
    }
}
