package io.quarkus.updates.core;

import static org.openrewrite.maven.Assertions.pomXml;

import java.nio.file.Path;

import org.junit.jupiter.api.Test;

import org.openrewrite.java.JavaParser;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;
import org.openrewrite.test.TypeValidation;

public class CoreUpdate324Test implements RewriteTest {

    @Override
    public void defaults(RecipeSpec spec) {
        CoreTestUtil.recipe(spec, Path.of("quarkus-updates", "core", "3.24.CR1.yaml"), "3.24.0.CR1")
                .parser(JavaParser.fromJavaVersion()
                        .classpath("quarkus-test-common")
                        .logCompilationWarningsAndErrors(true))
                .typeValidationOptions(TypeValidation.all());
    }

    @Test
    void testJpaModelgenOldDependency() {
        //language=xml
        rewriteRun(pomXml(
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencies>
                                <dependency>
                                    <groupId>org.hibernate</groupId>
                                    <artifactId>hibernate-jpamodelgen</artifactId>
                                    <version>6.4.3.Final</version>
                                </dependency>
                            </dependencies>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """,
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-processor</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """));
    }

    @Test
    void testJpaModelgenNewDependency() {
        //language=xml
        rewriteRun(pomXml(
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencies>
                                <dependency>
                                    <groupId>org.hibernate.orm</groupId>
                                    <artifactId>hibernate-jpamodelgen</artifactId>
                                    <version>6.1.2.Final</version>
                                    <scope>provided</scope>
                                </dependency>
                            </dependencies>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """,
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-processor</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """));
    }

    @Test
    void testJpaModelgenNewDependencyManagedByQuarkusBom() {
        //language=xml
        rewriteRun(pomXml(
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>3.23.0</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <dependencies>
                                <dependency>
                                    <groupId>org.hibernate.orm</groupId>
                                    <artifactId>hibernate-jpamodelgen</artifactId>
                                    <version>6.1.2.Final</version>
                                    <scope>provided</scope>
                                </dependency>
                            </dependencies>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """,
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>3.24.0.CR1</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-processor</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """));
    }

    @Test
    void testJpaModelgenExistingConfig() {
        //language=xml
        rewriteRun(pomXml(
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencies>
                                <dependency>
                                    <groupId>org.hibernate.orm</groupId>
                                    <artifactId>hibernate-jpamodelgen</artifactId>
                                    <version>6.1.2.Final</version>
                                </dependency>
                            </dependencies>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <proc>none</proc>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """,
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <proc>none</proc>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-processor</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """));
    }

    @Test
    void testJpaModelgenAnotherProcessor() {
        //language=xml
        rewriteRun(pomXml(
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencies>
                                <dependency>
                                    <groupId>org.hibernate.orm</groupId>
                                    <artifactId>hibernate-jpamodelgen</artifactId>
                                    <version>6.1.2.Final</version>
                                </dependency>
                            </dependencies>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <proc>none</proc>
                                            <annotationProcessorPaths>
                                                <annotationProcessorPath>
                                                    <groupId>another.annotation</groupId>
                                                    <artifactId>processor</artifactId>
                                                </annotationProcessorPath>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """,
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <proc>none</proc>
                                            <annotationProcessorPaths>
                                                <annotationProcessorPath>
                                                    <groupId>another.annotation</groupId>
                                                    <artifactId>processor</artifactId>
                                                </annotationProcessorPath>
                                                <annotationProcessorPath>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-processor</artifactId>
                                                </annotationProcessorPath>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """));
    }

    @Test
    void testJpaModelgenNewAnnotationProcessorAlreadyPresent() {
        //language=xml
        rewriteRun(pomXml(
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-jpamodelgen</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """,
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-processor</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """));
    }

    @Test
    void testJpaModelgenOldAnnotationProcessorAlreadyPresent() {
        //language=xml
        rewriteRun(pomXml(
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>3.23.0</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate</groupId>
                                                    <artifactId>hibernate-jpamodelgen</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """,
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>3.24.0.CR1</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-processor</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """));
    }

    @Test
    void testJpaModelgenNewAnnotationProcessorAlreadyPresentWithOutdatedVersion() {
        //language=xml
        rewriteRun(pomXml(
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>3.23.0</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate</groupId>
                                                    <artifactId>hibernate-jpamodelgen</artifactId>
                                                    <version>6.6.6.Final</version>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """,
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>3.24.0.CR1</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-processor</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """));
    }

    @Test
    void testJpaModelgenOldAnnotationProcessorAlreadyPresentWithOutdatedVersion() {
        //language=xml
        rewriteRun(pomXml(
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>3.23.0</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate</groupId>
                                                    <artifactId>hibernate-jpamodelgen</artifactId>
                                                    <version>5.6.15.Final</version>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """,
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>3.24.0.CR1</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-processor</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """));
    }

    @Test
    void testJpaModelgenNoBuildSection() {
        //language=xml
        rewriteRun(pomXml(
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>3.23.0</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <dependencies>
                                <dependency>
                                    <groupId>org.hibernate.orm</groupId>
                                    <artifactId>hibernate-jpamodelgen</artifactId>
                                    <version>6.1.2.Final</version>
                                    <scope>provided</scope>
                                </dependency>
                            </dependencies>
                        </project>
                        """,
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>3.24.0.CR1</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <build>
                                <plugins>
                                    <plugin>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-processor</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """));
    }

    @Test
    void testJpaModelgenNoMavenCompilerPlugin() {
        //language=xml
        rewriteRun(pomXml(
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>3.23.0</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <dependencies>
                                <dependency>
                                    <groupId>org.hibernate.orm</groupId>
                                    <artifactId>hibernate-jpamodelgen</artifactId>
                                    <version>6.1.2.Final</version>
                                    <scope>provided</scope>
                                </dependency>
                            </dependencies>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-jar-plugin</artifactId>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """,
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>3.24.0.CR1</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-jar-plugin</artifactId>
                                    </plugin>
                                    <plugin>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-processor</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """));
    }

    @Test
    void testSyncVersion() {
        //language=xml
        rewriteRun(pomXml(
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <properties>
                                <quarkus.version>3.23.0</quarkus.version>
                            </properties>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>${quarkus.version}</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-jpamodelgen</artifactId>
                                                    <version>6.2.13.Final</version>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """,
                """
                        <project>
                            <modelVersion>4.0.0</modelVersion>
                            <groupId>io.quarkus.bot</groupId>
                            <artifactId>release</artifactId>
                            <version>999-SNAPSHOT</version>
                            <properties>
                                <quarkus.version>3.24.0.CR1</quarkus.version>
                            </properties>
                            <dependencyManagement>
                                <dependencies>
                                    <dependency>
                                        <groupId>io.quarkus</groupId>
                                        <artifactId>quarkus-bom</artifactId>
                                        <version>${quarkus.version}</version>
                                        <type>pom</type>
                                        <scope>import</scope>
                                    </dependency>
                                </dependencies>
                            </dependencyManagement>
                            <build>
                                <plugins>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.12.1</version>
                                        <configuration>
                                            <annotationProcessorPaths>
                                                <path>
                                                    <groupId>org.hibernate.orm</groupId>
                                                    <artifactId>hibernate-processor</artifactId>
                                                </path>
                                            </annotationProcessorPaths>
                                        </configuration>
                                    </plugin>
                                </plugins>
                            </build>
                        </project>
                        """));
    }

}
